---
- name: Install and configure Apache  
  hosts: web_server
  become: true

  tasks:
    - name: Install httpd package
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Enable and start httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Open HTTP port in firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
